In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#Sentances
sent = [ 'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',]

In [3]:
##Define the Vocabulary size
voc_size = 10000

In [4]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6356, 1883, 3059, 190],
 [6356, 1883, 3059, 4313],
 [6356, 519, 3059, 5751],
 [1261, 9196, 9870, 7451, 907],
 [1261, 9196, 9870, 7451, 9609],
 [1605, 6356, 4041, 3059, 7442],
 [9206, 8577, 3669, 7451]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [11]:
print(embedded_docs)

[[   0    0    0    0 6356 1883 3059  190]
 [   0    0    0    0 6356 1883 3059 4313]
 [   0    0    0    0 6356  519 3059 5751]
 [   0    0    0 1261 9196 9870 7451  907]
 [   0    0    0 1261 9196 9870 7451 9609]
 [   0    0    0 1605 6356 4041 3059 7442]
 [   0    0    0    0 9206 8577 3669 7451]]


In [12]:
##Feature representation
dim = 10

In [23]:
# model =Sequential()
# model.add(Embedding(voc_size,dim, input_length=sent_length))
# model.compile('adam','mse')

model = Sequential()
model.add(Embedding(10000, 10, input_length=8))
model.compile(optimizer='adam', loss='mse')
model




<Sequential name=sequential_5, built=False>

In [1]:
model.weights()

NameError: name 'model' is not defined

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 528ms/step


array([[[-0.00650029,  0.04449124,  0.00268357,  0.03259077,
          0.03592714,  0.04967209, -0.04352934, -0.00743467,
          0.03110588, -0.02928548],
        [-0.00650029,  0.04449124,  0.00268357,  0.03259077,
          0.03592714,  0.04967209, -0.04352934, -0.00743467,
          0.03110588, -0.02928548],
        [-0.00650029,  0.04449124,  0.00268357,  0.03259077,
          0.03592714,  0.04967209, -0.04352934, -0.00743467,
          0.03110588, -0.02928548],
        [-0.00650029,  0.04449124,  0.00268357,  0.03259077,
          0.03592714,  0.04967209, -0.04352934, -0.00743467,
          0.03110588, -0.02928548],
        [ 0.04048998,  0.01947996,  0.03808782, -0.01596427,
         -0.00783331,  0.00764872, -0.03275616,  0.02449084,
         -0.0014356 ,  0.01416803],
        [ 0.04456856,  0.03816816,  0.02188853,  0.04057046,
         -0.00091528,  0.00948606, -0.02945071,  0.02875498,
          0.01330478,  0.01716653],
        [ 0.04244639, -0.02629869, -0.03828132,  0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 6356, 1883, 3059,  190], dtype=int32)